services:
  yolo:
    image: ${YOLO_IMAGE}
    ports:
      - "${YOLO_PORT}:${YOLO_PORT}"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - DB_BACKEND=${DB_BACKEND}
      - DATABASE_URL=${DATABASE_URL}
      - RABBITMQ_URL=${RABBITMQ_URL}
    depends_on:
      - postgres

  ollama-ui:
    image: ${OLLAMA_UI_IMAGE}
    ports:
      - "${OLLAMA_UI_PORT}:${OLLAMA_UI_PORT}"
    environment:
      - ENV=${ENV}
      - YOLO_SERVICE=${YOLO_SERVICE}
      - YOLO_SERVICE_DEV=${YOLO_SERVICE_DEV}

  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672" # AMQP port
      - "15672:15672" # Management UI port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
volumes:
  pgdata:
  rabbitmq_data:
